SRS 	= main.c ft_init.c get_dictionary.c check_dictionary.c ft_bloc3.c ft_putchar_trim.c get_values.c write_number.c

NAME	= rush-02

FLAGS	= -Wall -Werror -Wextra

all:		${NAME}

${NAME}:
			gcc ${FLAGS} -o ${NAME} ${SRS}

fclean:
			rm -f ${NAME}

re:			fclean all
